name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Omny Site Builder
        run: dotnet tool install -g Omny.Cms.Builder --prerelease

      - name: Build static site
        run: omnycms-builder

      - name: Sanitize branch name
        id: branch
        run: |
          RAW_NAME="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          SAFE_NAME="${RAW_NAME//\//-}"
          TRIMMED_NAME=$(echo "$SAFE_NAME" | cut -c1-15)
          CLEAN_NAME=$(echo "$TRIMMED_NAME" | sed 's/-$//')
          echo "branch=$CLEAN_NAME" >> "$GITHUB_OUTPUT"

      - name: Deploy to Cloudflare Workers (main)
        if: github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.26.0
          command: deploy

      - name: Deploy to Cloudflare Workers (preview)
        if: github.ref_name != 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.26.0
          command: versions upload --preview-alias ${{ steps.branch.outputs.branch }}
